spring.application.name=System Payout

spring.datasource.url=jdbc:postgresql://localhost:5432/systempayout
spring.datasource.username=postgres
spring.datasource.password=Matheus.909
spring.jpa.hibernate.ddl-auto=update